[package]
name = "RustWorld"
version = "0.1.0"
authors = ["29449 <2944972991@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"